export const books = [
  {
    id: 1,
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Fiction",
    imageUrl: "/assets/books/52578297.jpeg",
    available: true,
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-Help",
    imageUrl: "https://source.unsplash.com/400x600/?book,self-help",
    available: true,
  },
  {
    id: 3,
    title: "Project Hail Mary",
    author: "Andy Weir",
    category: "Sci-Fi",
    imageUrl: "https://source.unsplash.com/400x600/?book,science-fiction",
    available: true,
  },
  {
    id: 4,
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    category: "Literary Fiction",
    imageUrl: "https://source.unsplash.com/400x600/?book,literature",
    available: true,
  },
  {
    id: 5,
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    category: "Historical Fiction",
    imageUrl: "https://source.unsplash.com/400x600/?book,historical",
    available: true,
  },
  {
    id: 6,
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi",
    imageUrl: "https://source.unsplash.com/400x600/?book,sci-fi",
    available: true,
  },
  {
    id: 7,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Finance",
    imageUrl: "https://source.unsplash.com/400x600/?book,money",
    available: true,
  },
  {
    id: 8,
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    category: "Mystery",
    imageUrl: "https://source.unsplash.com/400x600/?book,mystery",
    available: true,
  },
  {
    id: 9,
    title: "The Song of Achilles",
    author: "Madeline Miller",
    category: "Historical Fiction",
    imageUrl: "https://source.unsplash.com/400x600/?book,mythology",
    available: true,
  },
  {
    id: 10,
    title: "Think Like a Monk",
    author: "Jay Shetty",
    category: "Self-Help",
    imageUrl: "https://source.unsplash.com/400x600/?book,meditation",
    available: true,
  },
  {
    id: 11,
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    category: "Fantasy",
    imageUrl: "https://source.unsplash.com/400x600/?book,fantasy",
    available: true,
  },
  {
    id: 12,
    title: "The Anthropocene Reviewed",
    author: "John Green",
    category: "Non-Fiction",
    imageUrl: "https://source.unsplash.com/400x600/?book,essays",
    available: true,
  },
  {
    id: 13,
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    category: "Fantasy",
    imageUrl: "https://source.unsplash.com/400x600/?book,magical",
    available: true,
  },
  {
    id: 14,
    title: "The Lincoln Highway",
    author: "Amor Towles",
    category: "Historical Fiction",
    imageUrl: "https://source.unsplash.com/400x600/?book,road-trip",
    available: true,
  },
  {
    id: 15,
    title: "The Final Girl Support Group",
    author: "Grady Hendrix",
    category: "Horror",
    imageUrl: "https://source.unsplash.com/400x600/?book,horror",
    available: true,
  },
  {
    id: 16,
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Fiction",
    imageUrl: "https://source.unsplash.com/400x600/?book,library",
    available: true,
  },
  {
    id: 17,
    title: "The Code Breaker",
    author: "Walter Isaacson",
    category: "Biography",
    imageUrl: "https://source.unsplash.com/400x600/?book,science",
    available: true,
  },
  {
    id: 18,
    title: "The Last Thing He Told Me",
    author: "Laura Dave",
    category: "Thriller",
    imageUrl: "https://source.unsplash.com/400x600/?book,thriller",
    available: true,
  },
  {
    id: 19,
    title: "The Four Winds",
    author: "Kristin Hannah",
    category: "Historical Fiction",
    imageUrl: "https://source.unsplash.com/400x600/?book,depression",
    available: true,
  },
  {
    id: 20,
    title: "The Push",
    author: "Ashley Audrain",
    category: "Psychological Thriller",
    imageUrl: "https://source.unsplash.com/400x600/?book,psychological",
    available: true,
  },
];
